name: Java CI/CD with Gradle and Dokku

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      # 1. Récupérer le code source
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Installer Java et Gradle
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '8.10.2'

      # 3. Construire l'application avec Gradle
      - name: Build with Gradle Wrapper
        run: ./gradlew build

      # 4. Exécuter les tests
      - name: Run Tests
        run: ./gradlew test

      # 5. Construire les images Docker (application uniquement)
      - name: Build Docker Image
        run: |
          docker build -t iwa_ms_admin_moderation-app-1:latest -f Dockerfile .

            # 6. Déployer sur Dokku
      - name: Debug SSH Configuration
        run: |
          echo "SSH PRIVATE KEY:"
          echo "${SSH_PRIVATE_KEY}" | head -n 5 # Affiche les 5 premières lignes (sans exposer toute la clé)
          echo "Checking ~/.ssh permissions"
          ls -la ~/.ssh || echo "SSH directory not found"
          echo "Known hosts content:"
          cat ~/.ssh/known_hosts || echo "Known hosts file not found"

      - name: Deploy App to Dokku
        env:
          DOKKU_HOST: ${{ secrets.DOKKU_HOST }}
          DOKKU_APP: iwa_ms_admin_moderation
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh

          echo "${SSH_PRIVATE_KEY}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          ssh-keyscan -H $DOKKU_HOST >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

          ssh -o StrictHostKeyChecking=no dokku@$DOKKU_HOST apps:list

          ssh dokku@$DOKKU_HOST apps:create $DOKKU_APP || true
          ssh dokku@$DOKKU_HOST postgres:create iwa_ms_admin_moderation_db || true
          ssh dokku@$DOKKU_HOST postgres:link iwa_ms_admin_moderation_db $DOKKU_APP || true
          ssh dokku@$DOKKU_HOST config:set $DOKKU_APP SPRING_DATASOURCE_USERNAME=postgres SPRING_DATASOURCE_PASSWORD=postgres
          docker save iwa_ms_admin_moderation-app-1:latest | bzip2 | ssh dokku@$DOKKU_HOST docker-import $DOKKU_APP
          ssh dokku@$DOKKU_HOST ps:restart $DOKKU_APP
      
